[2024-01-30T15:42:21.402+0000] {processor.py:161} INFO - Started process (PID=4423) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:42:21.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:42:21.406+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:42:21.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:42:21.464+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:42:21.465+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:42:21.467+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:42:21.468+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:42:21.468+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:42:21.468+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:42:21.469+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:42:21.469+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:42:21.469+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:42:21.469+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:42:21.470+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:42:21.470+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:42:21.474+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:42:21.470+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:42:21.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:42:21.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.115 seconds
[2024-01-30T15:42:51.950+0000] {processor.py:161} INFO - Started process (PID=4478) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:42:51.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:42:51.953+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:42:51.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:42:51.968+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:42:51.969+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:42:51.970+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:42:51.970+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:42:51.970+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:42:51.970+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:42:51.971+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:42:51.971+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:42:51.971+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:42:51.972+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:42:51.972+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:42:51.972+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:42:51.978+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:42:51.973+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:42:51.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:42:52.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.058 seconds
[2024-01-30T15:43:22.725+0000] {processor.py:161} INFO - Started process (PID=4533) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:43:22.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:43:22.731+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:43:22.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:43:22.753+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:43:22.753+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:43:22.754+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:43:22.754+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:43:22.754+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:43:22.755+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:43:22.755+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:43:22.755+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:43:22.757+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:43:22.757+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:43:22.757+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:43:22.758+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:43:22.763+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:43:22.758+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:43:22.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:43:22.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.066 seconds
[2024-01-30T15:43:53.557+0000] {processor.py:161} INFO - Started process (PID=4595) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:43:53.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:43:53.560+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:43:53.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:43:53.625+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:43:53.627+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:43:53.627+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:43:53.634+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:43:53.635+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:43:53.637+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:43:53.637+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:43:53.638+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:43:53.638+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:43:53.638+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:43:53.640+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:43:53.642+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:43:53.651+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:43:53.643+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:43:53.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:43:53.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.129 seconds
[2024-01-30T15:44:23.806+0000] {processor.py:161} INFO - Started process (PID=4651) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:44:23.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:44:23.809+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:44:23.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:44:23.826+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:44:23.827+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:44:23.827+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:44:23.828+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:44:23.828+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:44:23.828+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:44:23.828+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:44:23.829+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:44:23.829+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:44:23.829+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:44:23.829+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:44:23.830+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:44:23.834+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:44:23.830+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:44:23.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:44:23.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.050 seconds
[2024-01-30T15:44:54.120+0000] {processor.py:161} INFO - Started process (PID=4707) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:44:54.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:44:54.124+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:44:54.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:44:54.143+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:44:54.143+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:44:54.144+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:44:54.144+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:44:54.144+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:44:54.145+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:44:54.145+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:44:54.145+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:44:54.146+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:44:54.146+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:44:54.146+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:44:54.146+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:44:54.151+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:44:54.147+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:44:54.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:44:54.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.054 seconds
[2024-01-30T15:45:24.498+0000] {processor.py:161} INFO - Started process (PID=4763) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:45:24.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:45:24.501+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:45:24.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:45:24.517+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:45:24.518+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:45:24.518+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:45:24.519+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:45:24.519+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:45:24.519+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:45:24.520+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:45:24.520+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:45:24.520+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:45:24.521+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:45:24.521+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:45:24.521+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:45:24.526+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:45:24.522+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:45:24.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:45:24.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.094 seconds
[2024-01-30T15:45:54.636+0000] {processor.py:161} INFO - Started process (PID=4819) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:45:54.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:45:54.640+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:45:54.640+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:45:54.656+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:45:54.657+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:45:54.657+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:45:54.657+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:45:54.657+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:45:54.658+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:45:54.658+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:45:54.658+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:45:54.659+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:45:54.659+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:45:54.659+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:45:54.659+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:45:54.664+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:45:54.660+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:45:54.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:45:54.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.049 seconds
[2024-01-30T15:46:25.240+0000] {processor.py:161} INFO - Started process (PID=4876) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:46:25.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:46:25.242+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:46:25.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:46:25.260+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:46:25.260+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:46:25.261+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:46:25.261+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:46:25.261+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:46:25.262+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:46:25.262+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:46:25.262+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:46:25.262+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:46:25.263+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:46:25.263+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:46:25.263+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:46:25.268+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:46:25.264+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:46:25.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:46:25.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.050 seconds
[2024-01-30T15:46:55.976+0000] {processor.py:161} INFO - Started process (PID=4932) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:46:55.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:46:55.979+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:46:55.978+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:46:55.995+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:46:55.996+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:46:55.996+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:46:55.996+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:46:55.997+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:46:55.997+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:46:55.997+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:46:55.998+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:46:55.998+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:46:55.998+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:46:55.999+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:46:55.999+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:46:56.004+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:46:56.000+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:46:56.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:46:56.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.050 seconds
[2024-01-30T15:47:26.167+0000] {processor.py:161} INFO - Started process (PID=4988) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:47:26.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:47:26.170+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:47:26.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:47:26.188+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:47:26.188+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:47:26.188+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:47:26.189+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:47:26.189+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:47:26.189+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:47:26.190+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:47:26.190+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:47:26.190+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:47:26.191+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:47:26.191+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:47:26.191+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:47:26.196+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:47:26.192+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:47:26.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:47:26.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.050 seconds
[2024-01-30T15:47:41.640+0000] {processor.py:161} INFO - Started process (PID=5028) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:47:41.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:47:41.643+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:47:41.643+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:47:41.696+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:47:41.696+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:47:41.697+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:47:41.697+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:47:41.697+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:47:41.698+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:47:41.698+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:47:41.698+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:47:41.698+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:47:41.699+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:47:41.699+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:47:41.699+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:47:41.704+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:47:41.700+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:47:41.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:47:41.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.138 seconds
[2024-01-30T15:48:11.840+0000] {processor.py:161} INFO - Started process (PID=5084) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:48:11.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:48:11.843+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:48:11.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:48:11.859+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:48:11.859+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:48:11.860+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:48:11.860+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:48:11.861+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:48:11.861+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:48:11.861+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:48:11.862+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:48:11.862+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:48:11.862+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:48:11.862+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:48:11.863+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:48:11.867+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:48:11.863+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:48:11.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:48:11.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.049 seconds
[2024-01-30T15:48:42.769+0000] {processor.py:161} INFO - Started process (PID=5141) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:48:42.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:48:42.772+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:48:42.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:48:42.790+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:48:42.791+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:48:42.791+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:48:42.792+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:48:42.792+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:48:42.792+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:48:42.793+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:48:42.793+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:48:42.793+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:48:42.794+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:48:42.794+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:48:42.794+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:48:42.799+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:48:42.795+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:48:42.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:48:42.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.066 seconds
[2024-01-30T15:49:13.085+0000] {processor.py:161} INFO - Started process (PID=5197) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:49:13.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:49:13.088+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:49:13.088+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:49:13.102+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:49:13.103+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:49:13.103+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:49:13.104+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:49:13.104+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:49:13.104+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:49:13.104+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:49:13.105+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:49:13.105+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:49:13.106+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:49:13.110+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:49:13.114+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:49:13.119+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:49:13.115+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:49:13.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:49:13.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.056 seconds
[2024-01-30T15:49:43.915+0000] {processor.py:161} INFO - Started process (PID=5251) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:49:43.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:49:43.918+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:49:43.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:49:43.933+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:49:43.933+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:49:43.934+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:49:43.934+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:49:43.934+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:49:43.934+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:49:43.935+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:49:43.935+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:49:43.935+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:49:43.935+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:49:43.936+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:49:43.936+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:49:43.941+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:49:43.936+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:49:43.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:49:43.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.047 seconds
[2024-01-30T15:50:14.755+0000] {processor.py:161} INFO - Started process (PID=5307) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:50:14.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:50:14.758+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:50:14.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:50:14.775+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:50:14.775+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:50:14.776+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:50:14.776+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:50:14.777+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:50:14.777+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:50:14.777+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:50:14.777+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:50:14.778+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:50:14.778+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:50:14.778+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:50:14.778+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:50:14.783+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:50:14.779+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:50:14.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:50:14.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.053 seconds
[2024-01-30T15:50:45.649+0000] {processor.py:161} INFO - Started process (PID=5363) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:50:45.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:50:45.652+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:50:45.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:50:45.668+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:50:45.669+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:50:45.669+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:50:45.669+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:50:45.670+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:50:45.670+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:50:45.671+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:50:45.671+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:50:45.671+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:50:45.672+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:50:45.672+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:50:45.672+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:50:45.677+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:50:45.673+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:50:45.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:50:45.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.050 seconds
[2024-01-30T15:51:16.370+0000] {processor.py:161} INFO - Started process (PID=5419) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:51:16.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:51:16.373+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:51:16.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:51:16.389+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:51:16.390+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:51:16.390+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:51:16.391+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:51:16.391+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:51:16.391+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:51:16.392+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:51:16.392+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:51:16.392+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:51:16.393+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:51:16.393+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:51:16.393+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:51:16.398+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:51:16.394+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:51:16.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:51:16.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.050 seconds
[2024-01-30T15:51:47.061+0000] {processor.py:161} INFO - Started process (PID=5475) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:51:47.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:51:47.064+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:51:47.064+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:51:47.079+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:51:47.079+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:51:47.080+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:51:47.080+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:51:47.081+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:51:47.081+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:51:47.081+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:51:47.082+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:51:47.082+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:51:47.082+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:51:47.083+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:51:47.083+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:51:47.087+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:51:47.083+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:51:47.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:51:47.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.051 seconds
[2024-01-30T15:52:17.624+0000] {processor.py:161} INFO - Started process (PID=5531) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:52:17.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:52:17.627+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:52:17.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:52:17.653+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:52:17.654+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:52:17.654+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:52:17.655+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:52:17.656+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:52:17.656+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:52:17.657+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:52:17.657+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:52:17.657+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:52:17.658+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:52:17.658+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:52:17.659+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:52:17.667+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:52:17.659+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:52:17.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:52:17.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.065 seconds
[2024-01-30T15:52:48.490+0000] {processor.py:161} INFO - Started process (PID=5587) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:52:48.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:52:48.493+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:52:48.493+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:52:48.517+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:52:48.518+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:52:48.519+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:52:48.519+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:52:48.519+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:52:48.520+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:52:48.520+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:52:48.521+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:52:48.521+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:52:48.522+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:52:48.522+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:52:48.523+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:52:48.529+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:52:48.523+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:52:48.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:52:48.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.064 seconds
[2024-01-30T15:53:18.648+0000] {processor.py:161} INFO - Started process (PID=5643) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:53:18.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:53:18.651+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:53:18.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:53:18.668+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:53:18.669+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:53:18.669+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:53:18.669+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:53:18.670+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:53:18.670+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:53:18.670+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:53:18.671+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:53:18.671+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:53:18.671+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:53:18.672+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:53:18.672+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:53:18.676+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:53:18.672+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:53:18.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:53:18.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.051 seconds
[2024-01-30T15:53:48.938+0000] {processor.py:161} INFO - Started process (PID=5699) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:53:48.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:53:48.942+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:53:48.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:53:48.964+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T15:53:48.965+0000] {logging_mixin.py:188} INFO - Hello, these are the square roots from 0 to 9
[2024-01-30T15:53:48.965+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T15:53:48.966+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T15:53:48.966+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T15:53:48.967+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T15:53:48.967+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T15:53:48.968+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T15:53:48.969+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T15:53:48.969+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T15:53:48.970+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T15:53:48.970+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T15:53:48.977+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:53:48.971+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 41, in <module>
    test_task = simple_testask1()>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T15:53:48.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:53:48.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.063 seconds
[2024-01-30T15:54:01.616+0000] {processor.py:161} INFO - Started process (PID=5718) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:54:01.617+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:54:01.620+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:01.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:54:01.649+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:54:01.780+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:01.779+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:sample_python_dag
[2024-01-30T15:54:01.809+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:01.808+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:sample_python_dag
[2024-01-30T15:54:01.831+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:01.830+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:sample_python_dag
[2024-01-30T15:54:01.832+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:01.832+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:54:01.856+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:01.855+0000] {dag.py:3058} INFO - Creating ORM DAG for sample_python_dag
[2024-01-30T15:54:01.878+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:01.877+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:54:01.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.327 seconds
[2024-01-30T15:54:32.300+0000] {processor.py:161} INFO - Started process (PID=5774) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:54:32.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:54:32.316+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:32.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:54:32.503+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:54:32.541+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:32.541+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:54:32.574+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:54:32.574+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:54:32.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.320 seconds
[2024-01-30T15:55:02.791+0000] {processor.py:161} INFO - Started process (PID=5830) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:55:02.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:55:02.794+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:55:02.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:55:02.826+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:55:02.845+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:55:02.845+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:55:02.865+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:55:02.864+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:55:02.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.100 seconds
[2024-01-30T15:55:33.112+0000] {processor.py:161} INFO - Started process (PID=5886) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:55:33.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:55:33.117+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:55:33.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:55:33.137+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:55:33.173+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:55:33.172+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:55:33.203+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:55:33.203+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:55:33.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.131 seconds
[2024-01-30T15:56:03.540+0000] {processor.py:161} INFO - Started process (PID=5941) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:56:03.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:56:03.543+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:56:03.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:56:03.566+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:56:03.583+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:56:03.583+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:56:03.602+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:56:03.601+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:56:03.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.086 seconds
[2024-01-30T15:56:34.271+0000] {processor.py:161} INFO - Started process (PID=5997) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:56:34.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:56:34.275+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:56:34.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:56:34.302+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:56:34.326+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:56:34.325+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:56:34.346+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:56:34.346+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:56:34.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.115 seconds
[2024-01-30T15:57:05.205+0000] {processor.py:161} INFO - Started process (PID=6053) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:57:05.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:57:05.208+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:57:05.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:57:05.230+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:57:05.250+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:57:05.250+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:57:05.271+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:57:05.271+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:57:05.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.108 seconds
[2024-01-30T15:57:35.468+0000] {processor.py:161} INFO - Started process (PID=6109) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:57:35.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:57:35.471+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:57:35.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:57:35.490+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:57:35.509+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:57:35.508+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:57:35.527+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:57:35.526+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:57:35.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.081 seconds
[2024-01-30T15:58:05.586+0000] {processor.py:161} INFO - Started process (PID=6165) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:58:05.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:58:05.589+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:58:05.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:58:05.606+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:58:05.624+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:58:05.624+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:58:05.642+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:58:05.642+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:58:05.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.080 seconds
[2024-01-30T15:58:35.844+0000] {processor.py:161} INFO - Started process (PID=6221) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:58:35.845+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:58:35.847+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:58:35.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:58:35.866+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:58:35.884+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:58:35.884+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:58:35.905+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:58:35.904+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:58:35.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.087 seconds
[2024-01-30T15:59:06.644+0000] {processor.py:161} INFO - Started process (PID=6282) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:06.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:59:06.648+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:06.647+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:06.675+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:06.694+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:06.694+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:59:06.712+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:06.712+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T15:59:06.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.095 seconds
[2024-01-30T15:59:37.644+0000] {processor.py:161} INFO - Started process (PID=6339) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:37.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:59:37.648+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:37.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:37.690+0000] {processor.py:840} INFO - DAG(s) 'sample_python_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:37.714+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:37.714+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:59:37.736+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:37.736+0000] {dag.py:3823} INFO - Setting next_dagrun for sample_python_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T15:59:37.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.126 seconds
[2024-01-30T15:59:54.699+0000] {processor.py:161} INFO - Started process (PID=6369) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:54.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T15:59:54.706+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:54.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:54.747+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T15:59:54.843+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:54.843+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:Ramy_dag
[2024-01-30T15:59:54.854+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:54.854+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:Ramy_dag
[2024-01-30T15:59:54.861+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:54.861+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:Ramy_dag
[2024-01-30T15:59:54.862+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:54.862+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T15:59:54.874+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:54.874+0000] {dag.py:3058} INFO - Creating ORM DAG for Ramy_dag
[2024-01-30T15:59:54.885+0000] {logging_mixin.py:188} INFO - [2024-01-30T15:59:54.885+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-01-30T15:59:54.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.219 seconds
[2024-01-30T16:00:25.589+0000] {processor.py:161} INFO - Started process (PID=6428) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:00:25.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:00:25.592+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:00:25.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:00:25.638+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:00:25.664+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:00:25.663+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:00:25.686+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:00:25.686+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:00:25.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.125 seconds
[2024-01-30T16:00:55.897+0000] {processor.py:161} INFO - Started process (PID=6485) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:00:55.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:00:55.901+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:00:55.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:00:55.918+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:00:55.940+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:00:55.939+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:00:55.965+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:00:55.965+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:00:55.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.094 seconds
[2024-01-30T16:01:26.120+0000] {processor.py:161} INFO - Started process (PID=6541) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:01:26.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:01:26.123+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:01:26.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:01:26.162+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:01:26.200+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:01:26.199+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:01:26.238+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:01:26.238+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:01:26.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.170 seconds
[2024-01-30T16:01:55.370+0000] {processor.py:161} INFO - Started process (PID=6596) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:01:55.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:01:55.373+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:01:55.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:01:55.410+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T16:01:55.410+0000] {logging_mixin.py:188} INFO - Hello, these are 10 square roots
[2024-01-30T16:01:55.411+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T16:01:55.411+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T16:01:55.412+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T16:01:55.412+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T16:01:55.412+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T16:01:55.413+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T16:01:55.414+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T16:01:55.415+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T16:01:55.416+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T16:01:55.416+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T16:01:55.423+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:01:55.417+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 44, in <module>
    test_task>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T16:01:55.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:01:55.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.079 seconds
[2024-01-30T16:02:16.699+0000] {processor.py:161} INFO - Started process (PID=6627) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:02:16.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:02:16.703+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:02:16.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:02:16.752+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T16:02:16.753+0000] {logging_mixin.py:188} INFO - Hello, these are 10 square roots
[2024-01-30T16:02:16.754+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T16:02:16.754+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T16:02:16.754+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T16:02:16.755+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T16:02:16.755+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T16:02:16.755+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T16:02:16.756+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T16:02:16.756+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T16:02:16.757+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T16:02:16.757+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T16:02:16.763+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:02:16.757+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 44, in <module>
    test_task>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T16:02:16.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:02:16.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.088 seconds
[2024-01-30T16:02:47.050+0000] {processor.py:161} INFO - Started process (PID=6682) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:02:47.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:02:47.053+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:02:47.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:02:47.079+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T16:02:47.080+0000] {logging_mixin.py:188} INFO - Hello, these are 10 square roots
[2024-01-30T16:02:47.081+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T16:02:47.081+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T16:02:47.081+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T16:02:47.082+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T16:02:47.082+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T16:02:47.083+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T16:02:47.083+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T16:02:47.084+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T16:02:47.084+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T16:02:47.085+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T16:02:47.091+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:02:47.085+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 44, in <module>
    test_task>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T16:02:47.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:02:47.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.063 seconds
[2024-01-30T16:03:17.758+0000] {processor.py:161} INFO - Started process (PID=6738) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:03:17.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:03:17.760+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:03:17.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:03:17.804+0000] {logging_mixin.py:188} INFO - ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2024-01-30T16:03:17.805+0000] {logging_mixin.py:188} INFO - Hello, these are 10 square roots
[2024-01-30T16:03:17.808+0000] {logging_mixin.py:188} INFO - 0.0
[2024-01-30T16:03:17.812+0000] {logging_mixin.py:188} INFO - 1.0
[2024-01-30T16:03:17.813+0000] {logging_mixin.py:188} INFO - 1.4142135623730951
[2024-01-30T16:03:17.813+0000] {logging_mixin.py:188} INFO - 1.7320508075688772
[2024-01-30T16:03:17.815+0000] {logging_mixin.py:188} INFO - 2.0
[2024-01-30T16:03:17.815+0000] {logging_mixin.py:188} INFO - 2.23606797749979
[2024-01-30T16:03:17.816+0000] {logging_mixin.py:188} INFO - 2.449489742783178
[2024-01-30T16:03:17.817+0000] {logging_mixin.py:188} INFO - 2.6457513110645907
[2024-01-30T16:03:17.817+0000] {logging_mixin.py:188} INFO - 2.8284271247461903
[2024-01-30T16:03:17.818+0000] {logging_mixin.py:188} INFO - 3.0
[2024-01-30T16:03:17.831+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:03:17.819+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 44, in <module>
    test_task>>simple_testask2()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2024-01-30T16:03:17.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:03:17.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.166 seconds
[2024-01-30T16:03:42.739+0000] {processor.py:161} INFO - Started process (PID=6787) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:03:42.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:03:42.741+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:03:42.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:03:42.784+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:03:42.780+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 46, in <module>
    test_task>>test_task2
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-01-30T16:03:42.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:03:42.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.070 seconds
[2024-01-30T16:04:13.178+0000] {processor.py:161} INFO - Started process (PID=6843) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:04:13.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:04:13.181+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:04:13.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:04:13.223+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:04:13.213+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 46, in <module>
    test_task>>test_task2
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-01-30T16:04:13.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:04:13.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.070 seconds
[2024-01-30T16:04:43.430+0000] {processor.py:161} INFO - Started process (PID=6901) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:04:43.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:04:43.432+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:04:43.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:04:43.471+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:04:43.464+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 46, in <module>
    test_task>>test_task2
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-01-30T16:04:43.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:04:43.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.067 seconds
[2024-01-30T16:05:13.897+0000] {processor.py:161} INFO - Started process (PID=6958) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:13.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:05:13.900+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:05:13.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:13.948+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:05:13.938+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 46, in <module>
    test_task>>test_task2
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-01-30T16:05:13.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:13.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.092 seconds
[2024-01-30T16:05:44.673+0000] {processor.py:161} INFO - Started process (PID=7014) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:44.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:05:44.675+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:05:44.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:44.694+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:05:44.690+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 46, in <module>
    test_task>>test_task2
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-01-30T16:05:44.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:44.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.045 seconds
[2024-01-30T16:05:45.718+0000] {processor.py:161} INFO - Started process (PID=7015) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:45.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:05:45.722+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:05:45.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:45.807+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:05:45.929+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:05:45.929+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:05:45.950+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:05:45.950+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:05:45.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.263 seconds
[2024-01-30T16:06:16.971+0000] {processor.py:161} INFO - Started process (PID=7071) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:06:16.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:06:16.973+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:06:16.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:06:16.988+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:06:17.007+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:06:17.006+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:06:17.029+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:06:17.029+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:06:17.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.084 seconds
[2024-01-30T16:06:47.376+0000] {processor.py:161} INFO - Started process (PID=7127) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:06:47.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:06:47.378+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:06:47.378+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:06:47.399+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:06:47.420+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:06:47.420+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:06:47.439+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:06:47.439+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:06:47.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.097 seconds
[2024-01-30T16:07:17.595+0000] {processor.py:161} INFO - Started process (PID=7183) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:17.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:07:17.639+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:17.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:17.684+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:17.703+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:17.703+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:07:17.732+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:17.732+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:07:17.769+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.189 seconds
[2024-01-30T16:07:27.574+0000] {processor.py:161} INFO - Started process (PID=7208) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:27.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:07:27.577+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:27.576+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:27.613+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:27.744+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:27.744+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:07:27.761+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:27.760+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:07:27.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.218 seconds
[2024-01-30T16:07:57.995+0000] {processor.py:161} INFO - Started process (PID=7265) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:57.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:07:58.001+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:58.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:58.043+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:07:58.089+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:58.089+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:07:58.139+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:07:58.138+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:07:58.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.202 seconds
[2024-01-30T16:08:24.823+0000] {processor.py:161} INFO - Started process (PID=7309) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:08:24.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:08:24.832+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:08:24.831+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:08:24.905+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:08:24.899+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 42, in <module>
    t1 = simple_testask1()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 366, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 233, in __init__
    super().__init__(task_id=task_id, **kwargs_to_upstream, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 184, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 804, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'carré parfait' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-01-30T16:08:24.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:08:24.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.111 seconds
[2024-01-30T16:08:55.728+0000] {processor.py:161} INFO - Started process (PID=7367) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:08:55.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:08:55.730+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:08:55.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:08:55.763+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:08:55.754+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mon dag/squares_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mon dag/squares_dags.py", line 42, in <module>
    t1 = simple_testask1()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 366, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 233, in __init__
    super().__init__(task_id=task_id, **kwargs_to_upstream, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 184, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 804, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'carré parfait' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-01-30T16:08:55.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:08:55.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.058 seconds
[2024-01-30T16:09:15.438+0000] {processor.py:161} INFO - Started process (PID=7411) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:15.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:09:15.443+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:15.442+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:15.490+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:15.639+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:15.638+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:09:15.671+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:15.671+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:09:15.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.281 seconds
[2024-01-30T16:09:19.851+0000] {processor.py:161} INFO - Started process (PID=7414) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:19.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:09:19.854+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:19.854+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:19.934+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:19.947+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:19.946+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:09:19.976+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:19.975+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:09:20.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.181 seconds
[2024-01-30T16:09:50.454+0000] {processor.py:161} INFO - Started process (PID=7471) to work on /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:50.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mon dag/squares_dags.py for tasks to queue
[2024-01-30T16:09:50.458+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:50.458+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:50.490+0000] {processor.py:840} INFO - DAG(s) 'Ramy_dag' retrieved from /opt/airflow/dags/mon dag/squares_dags.py
[2024-01-30T16:09:50.583+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:50.583+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T16:09:50.602+0000] {logging_mixin.py:188} INFO - [2024-01-30T16:09:50.601+0000] {dag.py:3823} INFO - Setting next_dagrun for Ramy_dag to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T16:09:50.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mon dag/squares_dags.py took 0.178 seconds
